### ISSUE TITLE
Modify bookmap design

### ISSUE THREAD

**Issue by keberlein** [oasis-tcs/dita#29]
Goal of redesign is to remediate problems but avoid breaking backward compatibility.

Discussed at TC meeting on 14 March 2017:
https://lists.oasis-open.org/archives/dita/201703/msg00019.html

Discussed at TC meeting on 21 March 2017:
https://lists.oasis-open.org/archives/dita/201703/msg00025.html

Discussed at TC meeting on 23 May 2017, moved to stage 2 and assigned to Eric Sirois; design goal is to allow `<ditavalref>` before front matter, as well as a `<keydefs>` container to hold key definitions.

06 Feb 2018: Eric designated 26 February 2018 as the date by which the proposal would be submitted

Amber Swope and Robert Anderson volunteered to serve as stage two reviewers.

Lot of discussion on the proposal at TC 27 March 2018.

**Comment by keberlein** [comment]
Goal of redesign is to remediate problems but avoid breaking backward compatibility

**Comment by robander** [comment]
Discussed 12 Feb 2019 (as well as a few earlier meetings that didn't get noted here) https://lists.oasis-open.org/archives/dita/201902/msg00056.html

Expecting to merge this with #83 -- discussion Feb 12 led to decision to add `<amendments>` as a child of `<booklists>`, which will make it available in both front and back matter; if specified without `@href`, and change history information is available to be generated, this should indicate that the change list should be generated. The element will remain available at its current location in the back matter, because forcing current maps to move that into booklists does not seem worth the very minor benefit of only having one possible location in back matter.

**Comment by keberlein** [comment]
I agreed to take the stage three proposal over from Eric Sirois. I'm attaching a PDF that contains sections of the TC meeting minutes that pertain to this proposal.
[Issue-29.pdf](https://github.com/oasis-tcs/dita/files/3678681/Issue-29.pdf)

**Comment by robander** [comment]
Kris resubmitted this proposal at stage two due to all of the changes since Eric's version; voted to stage 3 again October 22, 2019.
