### ISSUE TITLE
Elements requiring sub elements

### ISSUE THREAD

**Issue by philiprbrenan** [oasis-tcs/dita#357]
Hi **Dita**:

The attached list [One.txt](https://github.com/oasis-tcs/dita/files/4558865/zzzDitaOne.txt) of 82 Dita 1.3 parent elements require at least one child element.  For example, a parent **ol** requires at least one **li** as a child. 8 other parent elements seem to require more than one child element [Several.txt](https://github.com/oasis-tcs/dita/files/4559251/zzzDitaSeveral.txt) , thus all other elements can be assumed not to require any child elements. 

From the point of view of making references between topics it would seem desirable that there should be no elements that require child elements because one might want to create a reference to, for example, an **ol** element before it has been populated with **li** elements.  Currently one has to add a bogus **li** element to achieve this.   Conversely, a list with one element is allowed even though a list of one element is no more or less a list than an empty list.  While these minor obstacles are easily surmounted  by human authors working on a small scale, they become ever more difficult to deal with at larger scales (using automation) as more and more of the shared corpus contains bogus entries simply to satisfy the DTDs.

Please consider, therefore, whether it would be desirable to allow all elements to be empty if needed in subsequent releases of Dita?

Thanks,

Phil

**Comment by robander** [comment]
Following up on this older issue, which appears to have been missed when it came in.

I think we've all been annoyed by this behavior in DITA 1.x releases when using conref, but I don't expect this is likely to change. For the few elements that have required children, we do get a lot of benefit out of that requirement; the biggest one is that many XML editors automatically insert those child elements simply because the grammar requires them. It also relieves some burden on tools, which would otherwise need to have error checking in place for each of these cases, just in case something like an empty `<ol>` element was encountered without any child elements. So, my suspicion is that these benefits would rule out making all of the child elements optional.

**Comment by keberlein** [comment]
We talked about this at the DITA TC meeting on 07 June 2022. The consensus was that current design of the DITA architecture with required child elements was the correct design. Yes, it leads to some minor inconveniences, but we think that the benefits of the design far out-weigh the minor annoyances.

I do apologize that it took us two years to respond to this issue, but the DITA TC is far more accustomed to receiving feedback through the OASIS dita-comment list than GitHub issues. We'll track feedback that comes in through the GitHub issue mechanism more rigorously moving forward.

Best,
Kristen James Eberlein
Chair, OASIS DITA Technical Committee
